version: "3.3"

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 2829:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db:/var/lib/postgresql/data